name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
      - edited
jobs:
  assign-label:
    env:
      # Now the title is evaluated outside the shell
      # And it will be treated as a string in the IF condition
      # The title is now a string and not a command
      # This is a security measure to prevent script injection
      TITLE: ${{ github.event.issue.title }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi